name: Push/CI

on:
  push:
    branches: []

# Set the access for individual scopes, or use permissions: write-all
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_TARGET_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_CODEARTIFACT_ROLE }}
          role-session-name: "GitHubActions-CodeArtifact"
          
      - name: AWS CodeArtifact Login
        run: aws codeartifact login --tool dotnet --repository BiSSkapp --domain swaltech --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --region ap-southeast-2

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore
        run: dotnet workload restore

      - name: Build
        run: dotnet build -c Release MPowerKit.TabView/MPowerKit.TabView.csproj

      - name: Pack
        run: dotnet pack -c Release MPowerKit.TabView/MPowerKit.TabView.csproj

      - name: Nuget Push
        run: dotnet nuget push MPowerKit.TabView/bin/Release/MPowerKit.TabView*.nupkg --source ${{ secrets.AWS_CODEARTIFACT_URL }} --skip-duplicate